version: '3.7'
services:
  airflow:
    image: apache/airflow:2.0.0-python3.8
    entrypoint: bash /opt/airflow/entrypoint.sh
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./entrypoint.sh:/opt/airflow/entrypoint.sh